# Generated by Django 4.2.2 on 2023-06-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrators',
            options={'verbose_name_plural': 'Administrators'},
        ),
        migrations.AlterModelOptions(
            name='airline_companies',
            options={'verbose_name_plural': 'Airline Companies'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='flights',
            options={'verbose_name_plural': 'Flights'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='user_roles',
            options={'verbose_name_plural': 'User Roles'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
