# Generated by Django 4.2.2 on 2023-06-20 21:31

import Bingo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0002_alter_administrators_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[Bingo.models.validate_nine_digits]),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='static/users/defaultuser.png', null=True, upload_to='users/'),
        ),
    ]
