# Generated by Django 4.2.2 on 2023-06-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0004_alter_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='/images/users/defaultuser.png', null=True, upload_to='users/'),
        ),
    ]
