# Generated by Django 4.2.2 on 2023-06-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0006_alter_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline_companies',
            name='logo',
            field=models.ImageField(blank=True, default='/airline_logos/airplanelogo.png', null=True, upload_to='airline_logos'),
        ),
    ]
