# Generated by Django 4.2.2 on 2023-08-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0014_alter_users_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='credit_card_no',
            field=models.CharField(max_length=16),
        ),
    ]
