# Generated by Django 4.2.2 on 2023-08-09 01:06

import Bingo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0015_alter_customers_credit_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255, validators=[Bingo.models.validate_password_strength]),
        ),
    ]
