# Generated by Django 4.2.2 on 2023-08-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0016_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline_companies',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='airline_logos/'),
        ),
    ]
