# Generated by Django 4.2.2 on 2023-08-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0017_alter_airline_companies_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='id',
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
