# Generated by Django 4.2.2 on 2023-08-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0019_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.TextField(max_length=255),
        ),
    ]
