# Generated by Django 4.2.2 on 2023-08-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0022_alter_tickets_itinerary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itinerary',
            new_name='Booking',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Bookings'},
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='itinerary',
            new_name='Booking',
        ),
    ]
