# Generated by Django 4.2.2 on 2023-08-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0024_airport_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='destination_country_id',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='origin_country_id',
        ),
    ]
