# Generated by Django 4.2.2 on 2023-08-24 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0025_remove_flights_destination_country_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='flight_number',
        ),
        migrations.AddField(
            model_name='flights',
            name='destination_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_flights', to='Bingo.airport'),
        ),
        migrations.AddField(
            model_name='flights',
            name='origin_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_flights', to='Bingo.airport'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='id',
            field=models.BigAutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
