# Generated by Django 4.2.2 on 2023-08-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0026_remove_flights_flight_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='destination_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flights', to='Bingo.airport'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='origin_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_flights', to='Bingo.airport'),
        ),
    ]
