# Generated by Django 4.2.2 on 2023-08-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0027_alter_flights_destination_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='flight_number',
            field=models.CharField(default='LY', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
