# Generated by Django 4.2.2 on 2023-08-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0028_flights_flight_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='flight_id',
        ),
        migrations.AddField(
            model_name='tickets',
            name='flight_number_ref',
            field=models.ForeignKey(db_column='flight_number', default='LY556', on_delete=django.db.models.deletion.CASCADE, to='Bingo.flights', to_field='flight_number'),
            preserve_default=False,
        ),
    ]
