# Generated by Django 4.2.2 on 2023-08-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0029_remove_tickets_flight_id_tickets_flight_number_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='flight_number_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bingo.flights', to_field='flight_number'),
        ),
    ]
