# Generated by Django 4.2.4 on 2023-08-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0030_alter_tickets_flight_number_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arrival_terminal',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='departure_terminal',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
    ]
