# Generated by Django 4.2.4 on 2023-09-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bingo', '0031_alter_flights_arrival_terminal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arrival_terminal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='departure_terminal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
